# Generated by Django 6.0.4 on 2026-04-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hexagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_id', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('value', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
    ]
